#!/bin/bash

# Lire un nombre de l'utilisateur
read -p "Entrez un nombre : " nombre

# Structure conditionnelle
if [ $nombre -gt 10 ]; then
    echo "Le nombre est supérieur à 10"
elif [ $nombre -eq 10 ]; then
    echo "Le nombre est égal à 10"
else
    echo "Le nombre est inférieur à 10"
fi
